name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build & publish
      run: dotnet publish -o /bin/Publish --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YoutubeDownloader
        path: /bin/Publish
